### ISSUE TITLE
1.8.3 vs 1.8.4

### ISSUE THREAD

**Issue by Heclalava** [XTLS/Xray-core#2538] opened 2023-09-09 23:31 UTC
I have noticed a dramatic drop in download speed since switching to 1.8.4. Before on 1.8.3 I would get 90 Mbps download through my VPS, now on 1.8.4 I never get more than 30 Mbps. 

I have been testing the last few days, by switching back and forwards between the 2 versions of the core on both my router and VPS, and it is definitely much faster on 1.8.3.

**Comment by KoinuDayo** [comment] 2023-09-09 23:33
请附上得出你这结论的图片，证明下

**Comment by Fangliding** [comment] 2023-09-09 23:34
What protocol are you using
What's the version of xray core on your server

**Comment by Heclalava** [comment] 2023-09-10 00:25
@KoinuDayo 
1.8.4
![1 8 4](https://github.com/XTLS/Xray-core/assets/8341359/cced6598-9761-40d0-8e17-384fb45d544b)

1.8.3
![1 8 3](https://github.com/XTLS/Xray-core/assets/8341359/43c12894-e7ef-4234-8f5e-c08dd4e3ea29)

Although 1.8.4 seems to be performing a little better now, but still a stark difference in speed between 1.8.4 and 1.8.3.

@Fangliding 
I am using xray REALITY. Both my router and VPS will either run 1.8.3 or 1.8.4 simultaneously when testing. Same core version on both VPS and router during each test.

**Comment by Fangliding** [comment] 2023-09-10 00:35
> @KoinuDayo 1.8.4 ![1 8 4](https://user-images.githubusercontent.com/8341359/266807858-cced6598-9761-40d0-8e17-384fb45d544b.png)
> 
> 1.8.3 ![1 8 3](https://user-images.githubusercontent.com/8341359/266807863-43c12894-e7ef-4234-8f5e-c08dd4e3ea29.png)
> 
> Although 1.8.4 seems to be performing a little better now, but still a stark difference in speed between 1.8.4 and 1.8.3.
> 
> @Fangliding I am using xray REALITY. Both my router and VPS will either run 1.8.3 or 1.8.4 simultaneously when testing. Same core version on both VPS and router during each test.

Did you use vision？
and did you try to use 1.8.3 server 1.8.4 client or 1.8.4 server 1.8.3 client
more comparisons help locate problem

**Comment by Heclalava** [comment] 2023-09-10 00:55
@Fangliding 

Yes I am using xtls-rprx-vision.

1.8.4 on VPS and 1.8.3 on router
![1 8 4_server_1 8 3_router](https://github.com/XTLS/Xray-core/assets/8341359/ee713edb-f233-421b-8e0c-6d62e40a468b)

1.8.3 on VPS and 1.8.4 on router
![1 8 3_server_1 8 4_router](https://github.com/XTLS/Xray-core/assets/8341359/aae7dc0e-967c-4358-89f5-1c477b1f86d2)

So it seems when the cores are not matched on the router and the VPS the speeds are similar. So the issue only appears when both the router and the VPS are on 1.8.4.

I am using the FancySS HND v8 plugin for Merlin Koolshare on Asus RT-AC86U. I downloaded the Xray-linux-arm64-v8a.zip from the 1.8.4 release, and compressed it with command `upx-ucl --lzma --ultra-brute xray`

I then upload that to my router by SCP to 192.168.0.1:/jffs/.koolshare/bin

**Comment by Fangliding** [comment] 2023-09-10 01:07
> @Fangliding
> 
> Yes I am using xtls-rprx-vision.
> 
> 1.8.4 on VPS and 1.8.3 on router ![1 8 4_server_1 8 3_router](https://user-images.githubusercontent.com/8341359/266808425-ee713edb-f233-421b-8e0c-6d62e40a468b.png)
> 
> 1.8.3 on VPS and 1.8.4 on router ![1 8 3_server_1 8 4_router](https://user-images.githubusercontent.com/8341359/266808433-aae7dc0e-967c-4358-89f5-1c477b1f86d2.png)
> 
> So it seems when the cores are not matched on the router and the VPS the speeds are similar. So the issue only appears when both the router and the VPS are on 1.8.4.
> 
> I am using the FancySS HND v8 plugin for Merlin Koolshare on Asus RT-AC86U. I downloaded the Xray-linux-arm64-v8a.zip from the 1.8.4 release, and compressed it with command `upx-ucl --lzma --ultra-brute xray`
> 
> I then upload that to my router by SCP to 192.168.0.1:/jffs/.koolshare/bin

It seem some feature added in 1.8.4 cause the problem. If one of server and client is 1.8.4, It will not function make the speed normal
Try to download xray core here https://github.com/XTLS/Xray-core/actions/runs/6009175068

you can find different xray core here https://github.com/XTLS/Xray-core/actions/workflows/release.yml
If the speed is normal, try a later build. If the speed is reduced, try an earlier build to locate the commit that caused the problem

**Comment by Heclalava** [comment] 2023-09-10 01:30
@Fangliding ok so that will take a while to test, just because of the length of time required to compress the core with upx. I will report back later if I manage to find the commit causing the problem.

**Comment by Fangliding** [comment] 2023-09-10 01:33
@Heclalava Is upx compress necessary? I think you can direct run client on pc, it can save much time

**Comment by Heclalava** [comment] 2023-09-10 01:39
> @Heclalava Is upx compress necessary? I think you can direct run client on pc, it can save much time

As I mostly use the router for xray, and this is where the issue is detected, I think continuing testing via the router is necessary. Also I believe v2rayA doesn't yet support xray reality vision yet. 
So because of the limited space on the jffs partition on the router, I do need to shrink it down with upx.

**Comment by Heclalava** [comment] 2023-09-10 01:58
@Fangliding the Xray-linux-arm64-v8a core from https://github.com/XTLS/Xray-core/actions/runs/6009175068 has the same issue. So I will have to try the older versions from https://github.com/XTLS/Xray-core/actions/workflows/release.yml

**Comment by Heclalava** [comment] 2023-09-10 02:33
@Fangliding this commit seems fine https://github.com/XTLS/Xray-core/actions/runs/5965516913. So it is one of the commits newer than this, that the problem seems have been introduced. I will continue testing to see if I can isolate the specific commit that causes the problem.

**Comment by Heclalava** [comment] 2023-09-10 04:45
@Fangliding the specific commit where the problem begins is https://github.com/XTLS/Xray-core/actions/runs/5983318167

Last working commit is with no issues is https://github.com/XTLS/Xray-core/actions/runs/5969608681

![image](https://github.com/XTLS/Xray-core/assets/8341359/a442c596-84ee-442e-998a-9902735e6f74)
Bottom one works fine, top one is the problem, and thereafter.

**Comment by Fangliding** [comment] 2023-09-10 05:55
> 

Will speed be affected if reality is not used?

**Comment by Heclalava** [comment] 2023-09-10 06:06
@Fangliding last good commit is https://github.com/XTLS/Xray-core/actions/runs/5966097424

Problems start from commit https://github.com/XTLS/Xray-core/actions/runs/5969608681

**Comment by Heclalava** [comment] 2023-09-10 06:07
> > 
> 
> Will speed be affected if reality is not used?

I think for now I will leave it in this commit that seems to be working and see how it goes for the next couple days, if any issues I will revert back to 1.8.3

**Comment by Fangliding** [comment] 2023-09-10 06:18
> @Fangliding last good commit is https://github.com/XTLS/Xray-core/actions/runs/5966097424
> 
> Problems start from commit https://github.com/XTLS/Xray-core/actions/runs/5969608681

I forgot one thing
only use the main branch build(https://github.com/XTLS/Xray-core/actions/workflows/release.yml?query=branch%3A%22main%22 ignore xxxxxx:main, it shoud not display), other banch might form other repo
And thank for your patience testing this

**Comment by Heclalava** [comment] 2023-09-10 06:32
> > @Fangliding last good commit is https://github.com/XTLS/Xray-core/actions/runs/5966097424
> > Problems start from commit https://github.com/XTLS/Xray-core/actions/runs/5969608681
> 
> I forgot one thing only use the main branch build(https://github.com/XTLS/Xray-core/actions/workflows/release.yml?query=branch%3A%22main%22 ignore xxxxxx:main, it shoud not display), other banch might form other repo And thank for your patience testing this

Ahh shit, I see there are a lot of commits between 1.8.3 and 1.8.4 to test. Hopefully I can narrow in when I know where I am getting problems and where I am not.

**Comment by StayAway32** [comment] 2023-09-11 13:09
well im also interested in the result so please keep on testing
i had the same problem but during switch from 1.8.1 to 1.8.4 i also switched from BBR to cubic since the RTT is 200 or above to my server
so i took it as the change from bbr to cubic and reverted back to using BBR again
if you found out that the cause is 1.8.4 i simply can revert server xray core to 1.8.3 and clients wont have a problem
thanks alot for your patience and testings
have a wonderful day

**Comment by Heclalava** [comment] 2023-09-12 02:31
@Fangliding testing I have hit an obstacle. A lot of the commits have expired, so unable to localize from which commit the problem starts:
![image](https://github.com/XTLS/Xray-core/assets/8341359/1d38716e-ea46-4b72-8e44-afdbf16a012e)

**Comment by Heclalava** [comment] 2023-09-12 02:35
It could be any of them from the 1.8.3 release up to the 1.8.4 release, but with most expired, it make testing very difficult.

**Comment by hkbase** [comment] 2023-09-13 10:27
我在服务端和客户端都使用最新的1.8.4版本，没有感受到网络性能降级，反而是感觉非常流畅，看youtube视频能够在极短的时间内跑满带宽，并且持续保持稳定。

**Comment by yzbleaf** [comment] 2023-11-02 03:54
I encountered the same problem. When I used 1.8.4 on the server, the speed was very slow. The web page sometimes took more than ten seconds to open. But when I restored it to 1.8.3, everything was normal. I am using xtls-rprx-vision.

**Comment by 1337anonboi** [comment] 2024-01-08 13:55
I can confirm that this is fixed on version 1.8.7.

---

我可以确认这个问题在1.8.7版本已经修复了。

**Comment by Fangliding** [comment] 2024-01-08 13:59
@1337anonboi great

**Comment by yuhan6665** [comment] 2024-01-08 16:00
ok

**Closed by yuhan6665** 2024-01-08 16:00 UTC
