### ISSUE TITLE
请问 Xray-core 的 DNS 模块是不支持 "expectIPs": ["geoip:!cn"] 吗？

### ISSUE THREAD

**Issue by GWONGJYULEI** [XTLS/Xray-core#627] opened 2021-06-30 02:42 UTC
以下是报错内容：
> Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid IP rule: [geoip:!cn] > infra/conf: failed to load GeoIP: !cn > infra/conf: code not found in geoip.dat: !CN

**Comment by hmol233** [comment] 2021-06-30 03:23
Duplicate of https://github.com/XTLS/Xray-core/issues/594

**Closed by hmol233** 2021-06-30 03:23 UTC
Labels: duplicate
